project_name: Default
working_dir: "."
cmd:
- python tests/inseq/test_inseq_methods.py
provisioning:
  gpu_type: h100
  gpu_count: 1
  cpu_count: 20
  ram: 160
teamcity:
  url: https://api.cadence.jetbrains.com
  build_conf_id: id8ecbe8985b5b416bB6c0782d6e8f7d2b_JetTrain
env:
  variables:
    PYTHONUNBUFFERED: "1"
  python:
    pip:
      requirements_path: requirements.txt
    version: 3.12.5
  secrets:
    variables: {}
    ssh_keys: []
  aws:
    sync_config: false
    sync_credentials: false
    sync_cache: false
project_sync:
  local:
    root: "."
    storage_name: Cadence Storage
    uri: ""
    exclude:
    - __pycache__
    - .git
    - '*.pyc'
    include: []
    sync_back: false
    snapshots: true
    storage_type: DEFAULT
inputs: []
outputs:
- type: OUTPUT
  storage_name: Cadence Storage
  uri: ""
  path: work/notebooks/output/inseq_methods_test
  acceleration: false
  storage_type: DEFAULT
mounts: []
storages: []
description: Runs Inseq attribution tests across different models and methods
