version: '3.8'

services:
  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./analyzer/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped

  visualizer:
    build:
      context: ./visualizer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://analyzer:8000
    depends_on:
      - analyzer
    restart: unless-stopped